### ISSUE TITLE
Actions menu description - why leave blank?

### ISSUE THREAD

**Issue by ewohnlich** [plone/plone.app.contentmenu#24]
A registered Action already has a description field, however the logic for building the menu doesn't use this https://github.com/plone/plone.app.contentmenu/blob/master/plone/app/contentmenu/menu.py#L115. It then passes an action with this empty description to the template, where it becomes an empty title attribute. Why don't we use action.get('description') here instead?

Note that the workflow menu does use the transition descriptions in its menu in this manner already. I know cut/copy/paste are probably self explanatory but I have some custom actions on my site that could warrant a bit more information.

**Comment by gforcada** [comment]
@ewohnlich I find this a great idea, would you have time to create such a PR? 🍀 👍🏾

**Comment by kshitiz305** [comment]
HI Team , @gforcada ,
Can I create a pull request for the same with the changes.

**Comment by gforcada** [comment]
@kshitiz305 yes please! create a PR on your own fork and send it over here to get merged 😄

**Comment by gforcada** [comment]
Sorry, I was pretty busy/tired these last weeks, I did a review of it 👍🏾
