### ISSUE TITLE
Renaming item that is default view of folder changes folder's default view back to "standard view"

### ISSUE THREAD

**Issue by jnachtigall** [plone/plone.app.contentmenu#3]
Steps to reproduce:
1. Take a fresh Plone 4.3.2 (the 'front-page' is the selected default page view here, but this bug occurs with all items that are selected as default page views of a folder, when they are renamed)
2. Rename 'front-page' to 'new-front-page'
3. 'new-front-page' is not the default page view anymore but the folder switched back to "standard view"

I would rather expect that renaming an article means that current relations remain as they are. This also means if it is currently the default view of a folder, then renaming does not break this

PS I do not know if this is an issue of p.a.contentmenu. If not, please forward it to a more appropriate module as I do not know any better.

**Comment by jensens** [comment]
IIRC this was fixed
