### ISSUE TITLE
Menu "Add new... -> Add item to default page" does not work

### ISSUE THREAD

**Issue by sverbois** [plone/plone.app.contentmenu#54]
In Plone 6.0.5 with plone.app.contentmenu 3.0.2,

- Add a new content type TTW in http://0.0.0.0:8080/Plone/@@dexterity-types named "Cover"
- Allow "File" and "Image" in "Contained items" field
- Check "Can be used as a default page" for the content type "Cover" in http://0.0.0.0:8080/Plone/@@content-controlpanel
- Create a content "Folder" in your site named "A folder"
- Create a content "Cover" in your folder named "My cover"
- Set "My cover" as default view in "Display" menu of "A folder"

When you want to add a new item ("File" or "Image") with the "Add new... -> Add item to default page" in "My cover" the modal form is not working.

The solution to this problem is to add an attribute data-pat-plone-modal="{"actionOptions": {"disableAjaxFormSubmit": True}" in the "a" tag of the "Add item to default page" link.

**Comment by laulaz** [comment]
See also https://github.com/plone/Products.CMFPlone/issues/3511
